### ISSUE TITLE
Expansion failing

### ISSUE THREAD

**Issue by sebw** [fiskhest/sxhkd-helper-menu#3]
That's me again :D 

This doesn't get expanding correctly:

```
{XF86Display,super + m}                                                         
    $HOME/.config/rofi/monitor.sh
```

Instead of display `super + m`, it shows `superm` here.

Can you reproduce?

Cheers!

**Comment by fiskhest** [comment]
Can reproduce - it boils down to a terrible solution for matching the various types of expansions and how they should be formatted before being returned to printout.

In the future that whole part of the code can definitely be improved but for now I think I figured out a simple fix that doesn't break any of the test configurations I've matched against in the past.  I've pushed version 0.3.7 which resolves this issue.
